env_variables:
  MONGO_USERNAME: ${MONGO_USERNAME}
  MONGO_PASSWORD: ${MONGO_PASSWORD}
  # FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
  # FIREBASE_PRIVATE_KEY_ID: ${FIREBASE_PRIVATE_KEY_ID}
  # FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
  # FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
  # FIREBASE_CLIENT_ID: ${FIREBASE_CLIENT_ID}
  # FIREBASE_CLIENT_x509_CERT_URL: ${FIREBASE_CLIENT_x509_CERT_URL}